export const LISTING_AMENITIES = [
  { key: 'airConditioning', label: 'Air Conditioning' },
  { key: 'furnished', label: 'Furnished' },
  { key: 'inUnitLaundry', label: 'In-Unit Laundry' },
  { key: 'sharedLaundry', label: 'Shared Laundry' },
  { key: 'laundryHookups', label: 'Laundry Hookups' },
  { key: 'balconyPatio', label: 'Balcony/Patio' },
  { key: 'yardGarden', label: 'Yard/Garden' },
  { key: 'parkingAvailable', label: 'Parking Available' },
  { key: 'petFriendly', label: 'Pet-Friendly' },
  { key: 'dishwasher', label: 'Dishwasher' },
  { key: 'microwave', label: 'Microwave' },
  { key: 'refrigerator', label: 'Refrigerator' },
  { key: 'stoveOven', label: 'Stove/Oven' },
  { key: 'hardwoodFloors', label: 'Hardwood Floors' },
  { key: 'carpet', label: 'Carpet' },
  { key: 'tileFloors', label: 'Tile Floors' },
  { key: 'centralHeating', label: 'Central Heating' },
  { key: 'fireplace', label: 'Fireplace' },
  { key: 'walkinClosets', label: 'Walk-in Closets' },
  { key: 'storageUnit', label: 'Storage Unit' },
  { key: 'gymFitness', label: 'Gym/Fitness Center' },
  { key: 'pool', label: 'Pool' },
  { key: 'securitySystem', label: 'Security System' },
  { key: 'highSpeedInternet', label: 'High Speed Internet' },
  { key: 'garage', label: 'Garage' },
  { key: 'elevator', label: 'Elevator' },
  { key: 'wheelchairAccessible', label: 'Wheelchair Accessible' }
];
