import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { HqsItem, HQS_CATEGORIES } from '@/hooks/useHqsChecklist';
import { format, parseISO } from 'date-fns';

interface Hqs52Meta {
  inspectionDate: string;
  propertyId: string;
  inspectionId: string;
}

export async function generateHqs52Pdf(items: HqsItem[], meta: Hqs52Meta) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(16);
  doc.text('HQS Inspection Report (Form HQS-52)', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Inspection Date: ${format(parseISO(meta.inspectionDate), 'MMMM d, yyyy')}`, 14, 32);
  doc.text(`Inspection ID: ${meta.inspectionId.slice(0, 8)}`, 14, 38);
  doc.text(`Property: ${meta.propertyId.slice(0, 8)}`, 14, 44);

  // Summary
  const totalItems = items.length;
  const passed = items.filter(i => i.passed === true).length;
  const failed = items.filter(i => i.passed === false).length;
  const pending = items.filter(i => i.passed === null).length;
  const overallResult = failed > 0 ? 'FAIL' : pending > 0 ? 'INCOMPLETE' : 'PASS';

  doc.setFontSize(12);
  doc.setFont(undefined!, 'bold');
  doc.text(`Overall Result: ${overallResult}`, pageWidth - 14, 32, { align: 'right' });
  doc.setFont(undefined!, 'normal');
  doc.setFontSize(10);
  doc.text(`Pass: ${passed}  |  Fail: ${failed}  |  Pending: ${pending}  |  Total: ${totalItems}`, pageWidth - 14, 39, { align: 'right' });

  // Line
  doc.setDrawColor(200);
  doc.line(14, 50, pageWidth - 14, 50);

  let startY = 56;

  // Category tables
  for (const cat of HQS_CATEGORIES) {
    const catItems = items.filter(i => i.category === cat.key);
    if (!catItems.length) continue;

    const catPassed = catItems.filter(i => i.passed === true).length;
    const catFailed = catItems.filter(i => i.passed === false).length;

    doc.setFontSize(11);
    doc.setFont(undefined!, 'bold');
    doc.text(`${cat.label}`, 14, startY);
    doc.setFont(undefined!, 'normal');
    doc.setFontSize(9);
    doc.text(`(${catPassed} pass, ${catFailed} fail)`, 14 + doc.getTextWidth(cat.label + '  '), startY);

    const tableBody = catItems.map(item => [
      item.item_name,
      item.passed === true ? 'PASS' : item.passed === false ? 'FAIL' : '—',
      item.deficiency_notes || '',
      item.photo_required ? 'Yes' : '',
    ]);

    autoTable(doc, {
      startY: startY + 3,
      head: [['Item', 'Result', 'Deficiency Notes', 'Photo Req.']],
      body: tableBody,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 20, halign: 'center' },
        2: { cellWidth: 80 },
        3: { cellWidth: 20, halign: 'center' },
      },
      didParseCell: (data) => {
        if (data.column.index === 1 && data.section === 'body') {
          const val = data.cell.raw as string;
          if (val === 'FAIL') {
            data.cell.styles.textColor = [220, 38, 38];
            data.cell.styles.fontStyle = 'bold';
          } else if (val === 'PASS') {
            data.cell.styles.textColor = [22, 163, 74];
          }
        }
      },
    });

    startY = (doc as any).lastAutoTable.finalY + 8;

    // Page break if near bottom
    if (startY > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      startY = 20;
    }
  }

  // Deficiency summary page
  const deficiencies = items.filter(i => i.passed === false && i.deficiency_notes);
  if (deficiencies.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.text('Deficiency Summary', pageWidth / 2, 20, { align: 'center' });

    autoTable(doc, {
      startY: 28,
      head: [['Category', 'Item', 'Deficiency Notes']],
      body: deficiencies.map(d => {
        const catLabel = HQS_CATEGORIES.find(c => c.key === d.category)?.label || d.category;
        return [catLabel, d.item_name, d.deficiency_notes || ''];
      }),
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [220, 38, 38], textColor: 255 },
    });
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(`Generated by OpenKey Housing Platform — Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' });
    doc.setTextColor(0);
  }

  doc.save(`HQS-52_Inspection_${meta.inspectionId.slice(0, 8)}.pdf`);
}
