-- Create platform_formulas table for documenting calculation formulas
CREATE TABLE public.platform_formulas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  formula TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('financial', 'performance', 'occupancy', 'investment', 'health')),
  variables JSONB DEFAULT '[]'::jsonb,
  mock_example JSONB DEFAULT '{}'::jsonb,
  used_in TEXT[] DEFAULT '{}',
  is_system BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.platform_formulas ENABLE ROW LEVEL SECURITY;

-- Admins can view all formulas
CREATE POLICY "Admins can view formulas"
ON public.platform_formulas
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.system_admins sa
    WHERE sa.user_id = auth.uid() AND sa.is_active = true
  )
);

-- Admins can create formulas
CREATE POLICY "Admins can create formulas"
ON public.platform_formulas
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.system_admins sa
    WHERE sa.user_id = auth.uid() AND sa.is_active = true
  )
);

-- Admins can update formulas
CREATE POLICY "Admins can update formulas"
ON public.platform_formulas
FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.system_admins sa
    WHERE sa.user_id = auth.uid() AND sa.is_active = true
  )
);

-- Admins can delete non-system formulas
CREATE POLICY "Admins can delete non-system formulas"
ON public.platform_formulas
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.system_admins sa
    WHERE sa.user_id = auth.uid() AND sa.is_active = true
  )
  AND is_system = false
);

-- Create updated_at trigger
CREATE TRIGGER update_platform_formulas_updated_at
BEFORE UPDATE ON public.platform_formulas
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Seed initial system formulas
INSERT INTO public.platform_formulas (name, description, formula, category, variables, mock_example, used_in, is_system) VALUES
(
  'Return on Investment (ROI)',
  'Measures the profitability of a property investment relative to its purchase price',
  '(Annual NOI / Purchase Price) × 100',
  'investment',
  '[{"name": "Annual NOI", "description": "Net Operating Income for the year"}, {"name": "Purchase Price", "description": "Original purchase price of the property"}]',
  '{"inputs": {"Annual NOI": 24000, "Purchase Price": 300000}, "calculation": "(24000 / 300000) × 100", "result": "8%"}',
  ARRAY['Property Analytics', 'Portfolio Dashboard', 'Investment Reports'],
  true
),
(
  'Net Operating Income (NOI)',
  'Total income generated by a property minus operating expenses, excluding mortgage payments',
  'Gross Revenue - Operating Expenses',
  'financial',
  '[{"name": "Gross Revenue", "description": "Total rental income and other property revenue"}, {"name": "Operating Expenses", "description": "Property taxes, insurance, maintenance, management fees, etc."}]',
  '{"inputs": {"Gross Revenue": 50000, "Operating Expenses": 18000}, "calculation": "50000 - 18000", "result": "$32,000"}',
  ARRAY['Property Analytics', 'Financial Reports', 'Portfolio Summary'],
  true
),
(
  'Occupancy Rate',
  'Percentage of units that are currently occupied by tenants',
  '(Occupied Units / Total Units) × 100',
  'occupancy',
  '[{"name": "Occupied Units", "description": "Number of units with active tenants"}, {"name": "Total Units", "description": "Total number of rentable units"}]',
  '{"inputs": {"Occupied Units": 45, "Total Units": 50}, "calculation": "(45 / 50) × 100", "result": "90%"}',
  ARRAY['Dashboard', 'Portfolio Metrics', 'Property Details'],
  true
),
(
  'Collection Rate',
  'Percentage of expected rent that has been successfully collected',
  '(Collected Rent / Expected Rent) × 100',
  'financial',
  '[{"name": "Collected Rent", "description": "Total rent actually received"}, {"name": "Expected Rent", "description": "Total rent that was due for the period"}]',
  '{"inputs": {"Collected Rent": 45000, "Expected Rent": 48000}, "calculation": "(45000 / 48000) × 100", "result": "93.75%"}',
  ARRAY['Payment Overview', 'Financial Analytics', 'Portfolio Health'],
  true
),
(
  'Capitalization Rate (Cap Rate)',
  'Rate of return on a property based on expected income, used to estimate investment potential',
  '(Annual NOI / Property Value) × 100',
  'investment',
  '[{"name": "Annual NOI", "description": "Net Operating Income for the year"}, {"name": "Property Value", "description": "Current market value of the property"}]',
  '{"inputs": {"Annual NOI": 32000, "Property Value": 400000}, "calculation": "(32000 / 400000) × 100", "result": "8%"}',
  ARRAY['Property Analytics', 'Investment Analysis', 'Market Comparison'],
  true
),
(
  'Expense Ratio',
  'Percentage of gross income consumed by operating expenses',
  '(Operating Expenses / Gross Revenue) × 100',
  'financial',
  '[{"name": "Operating Expenses", "description": "Total operating costs for the property"}, {"name": "Gross Revenue", "description": "Total income from the property"}]',
  '{"inputs": {"Operating Expenses": 18000, "Gross Revenue": 50000}, "calculation": "(18000 / 50000) × 100", "result": "36%"}',
  ARRAY['Financial Reports', 'Property Analytics', 'Budget Planning'],
  true
),
(
  'Break-even Occupancy',
  'Minimum occupancy rate needed to cover all operating expenses',
  '(Operating Expenses / Potential Gross Income) × 100',
  'occupancy',
  '[{"name": "Operating Expenses", "description": "Total operating costs"}, {"name": "Potential Gross Income", "description": "Maximum possible income if 100% occupied"}]',
  '{"inputs": {"Operating Expenses": 18000, "Potential Gross Income": 60000}, "calculation": "(18000 / 60000) × 100", "result": "30%"}',
  ARRAY['Investment Analysis', 'Risk Assessment'],
  true
),
(
  'Cash-on-Cash Return',
  'Annual return on the actual cash invested (down payment and closing costs)',
  '(Annual Cash Flow / Total Cash Invested) × 100',
  'investment',
  '[{"name": "Annual Cash Flow", "description": "Net cash flow after all expenses and debt service"}, {"name": "Total Cash Invested", "description": "Down payment plus closing costs and initial repairs"}]',
  '{"inputs": {"Annual Cash Flow": 8000, "Total Cash Invested": 60000}, "calculation": "(8000 / 60000) × 100", "result": "13.3%"}',
  ARRAY['Investment Reports', 'Property Analytics'],
  true
),
(
  'Rent Health Score',
  'Gamified score (0-100) measuring overall rent collection health with penalties for late and unpaid rent',
  'Base Score (100) - Late Penalties - Unpaid Penalties + On-Time Bonuses',
  'health',
  '[{"name": "Base Score", "description": "Starting score of 100"}, {"name": "Late Penalties", "description": "Points deducted for late payments (-5 per late unit)"}, {"name": "Unpaid Penalties", "description": "Points deducted for unpaid rent (-10 per unpaid unit)"}, {"name": "On-Time Bonuses", "description": "Bonus points for consistent on-time payments"}]',
  '{"inputs": {"Base Score": 100, "Late Units": 2, "Unpaid Units": 1, "On-Time Streak": 3}, "calculation": "100 - (2 × 5) - (1 × 10) + (3 × 2)", "result": "86"}',
  ARRAY['Payment Overview', 'Dashboard'],
  true
),
(
  'Portfolio Health Score',
  'Weighted average combining occupancy, collection rate, and maintenance metrics',
  '(Occupancy × 0.4) + (Collection Rate × 0.4) + (Maintenance Score × 0.2)',
  'health',
  '[{"name": "Occupancy", "description": "Current occupancy rate percentage"}, {"name": "Collection Rate", "description": "Rent collection rate percentage"}, {"name": "Maintenance Score", "description": "Score based on maintenance request resolution time and backlog"}]',
  '{"inputs": {"Occupancy": 90, "Collection Rate": 95, "Maintenance Score": 80}, "calculation": "(90 × 0.4) + (95 × 0.4) + (80 × 0.2)", "result": "78%"}',
  ARRAY['Portfolio Dashboard', 'Admin Analytics'],
  true
);