-- Insert test notifications for landlord users to test navigation logic
INSERT INTO public.notifications (user_id, title, description, type, link, metadata, read) VALUES
-- Get a landlord user ID (assuming landlord@openkey.com exists)
((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'New Tenant Application Received', 
 'A new application has been submitted for your property at 123 Main Street. The applicant has completed all required documents and paid the application fee.',
 'application_received',
 '/applications',
 '{"property_id": "123", "property_address": "123 Main Street"}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Urgent Maintenance Request', 
 'Emergency plumbing issue reported at 456 Oak Avenue. Tenant reports water leak in bathroom ceiling. Immediate attention required.',
 'maintenance_urgent',
 '/maintenance-requests',
 '{"property_id": "456", "priority": "urgent", "category": "plumbing"}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Rent Payment Received', 
 'Monthly rent payment of $1,850 has been successfully processed for 789 Pine Street. Payment received via ACH transfer.',
 'payment_received',
 '/dashboard?tab=payments',
 '{"amount": 1850, "property_id": "789", "payment_method": "ACH"}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Lease Expiring in 30 Days', 
 'The lease for your tenant at 321 Elm Street will expire on January 15, 2025. Consider reaching out to discuss renewal options.',
 'lease_expiring_soon',
 '/dashboard?tab=properties',
 '{"property_id": "321", "expiry_date": "2025-01-15", "days_remaining": 30}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Payment Overdue Notice', 
 'Rent payment for 555 Maple Drive is now 5 days overdue. Last payment was due on November 1st. Consider sending a reminder notice.',
 'payment_overdue',
 '/dashboard?tab=payments',
 '{"property_id": "555", "days_overdue": 5, "amount_due": 1200}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Maintenance Request Completed', 
 'The kitchen appliance repair at 999 Cedar Lane has been completed by our maintenance team. Tenant has been notified and work order closed.',
 'maintenance_request',
 '/maintenance-requests',
 '{"property_id": "999", "work_order": "WO-2024-1156", "status": "completed"}',
 true),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Application Update Required', 
 'The application for 777 Broadway requires additional documentation. The applicant needs to submit proof of employment and updated bank statements.',
 'application_update',
 '/applications',
 '{"application_id": "APP-2024-445", "missing_docs": ["employment_proof", "bank_statements"]}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Inspection Scheduled', 
 'Annual property inspection has been scheduled for 888 Valley Road on December 20th at 2:00 PM. Tenant has been notified.',
 'inspection_scheduled',
 '/dashboard?tab=properties',
 '{"property_id": "888", "inspection_date": "2024-12-20", "inspector": "ABC Property Inspections"}',
 true),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Lease Renewal Signed', 
 'Great news! Your tenant at 444 Oak Street has signed the lease renewal for another 12 months starting February 1st, 2025.',
 'lease_renewal',
 '/dashboard?tab=properties',
 '{"property_id": "444", "renewal_start": "2025-02-01", "duration": "12 months"}',
 false),

((SELECT id FROM auth.users WHERE email = 'landlord@openkey.com'), 
 'Security Deposit Request', 
 'Tenant at 222 Birch Avenue is requesting return of security deposit following move-out inspection. Property cleaned and in good condition.',
 'security_deposit',
 '/dashboard?tab=finances',
 '{"property_id": "222", "deposit_amount": 1500, "status": "approved"}',
 false);