-- Replace broken placeholder URLs with SVG data URIs for gift cards
UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#00704A"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Starbucks</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Starbucks%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#FF9900"/><text x="200" y="130" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Amazon</text><text x="200" y="160" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Amazon%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#007AFF"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Apple</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Apple%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#4285F4"/><text x="200" y="120" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Google Play</text><text x="200" y="150" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="180" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Google Play%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#E50914"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Netflix</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Netflix%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#0071CE"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Walmart</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Walmart%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#CC0000"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Target</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Target%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#003BB3"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Best Buy</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Best Buy%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#FF6600"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Home Depot</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Home Depot%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#004990"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Lowe''s</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Lowe''s%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#1A237E"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Visa</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Visa%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#FF3008"/><text x="200" y="130" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="24" font-weight="bold">DoorDash</text><text x="200" y="160" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%DoorDash%';

UPDATE public.rewards SET image_url = 'data:image/svg+xml;base64,' || encode('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#00D4AA"/><text x="200" y="130" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Uber Eats</text><text x="200" y="160" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="18">Gift Card</text><text x="200" y="190" text-anchor="middle" fill="black" font-family="Arial, sans-serif" font-size="20" font-weight="bold">$' || points_cost/100 || '</text></svg>', 'base64') WHERE name LIKE '%Uber Eats%';