-- Insert all world countries (upsert to avoid duplicates with existing 8)
INSERT INTO countries (id, name, iso_code_2, iso_code_3, currency_code, phone_prefix, address_format, is_active)
VALUES
  ('AF', 'Afghanistan', 'AF', 'AFG', 'AFN', '+93', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('AL', 'Albania', 'AL', 'ALB', 'ALL', '+355', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('DZ', 'Algeria', 'DZ', 'DZA', 'DZD', '+213', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('AD', 'Andorra', 'AD', 'AND', 'EUR', '+376', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('AO', 'Angola', 'AO', 'AGO', 'AOA', '+244', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('AG', 'Antigua and Barbuda', 'AG', 'ATG', 'XCD', '+1-268', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('AR', 'Argentina', 'AR', 'ARG', 'ARS', '+54', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('AM', 'Armenia', 'AM', 'ARM', 'AMD', '+374', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('AT', 'Austria', 'AT', 'AUT', 'EUR', '+43', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('AZ', 'Azerbaijan', 'AZ', 'AZE', 'AZN', '+994', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BS', 'Bahamas', 'BS', 'BHS', 'BSD', '+1-242', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BH', 'Bahrain', 'BH', 'BHR', 'BHD', '+973', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BD', 'Bangladesh', 'BD', 'BGD', 'BDT', '+880', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BB', 'Barbados', 'BB', 'BRB', 'BBD', '+1-246', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BY', 'Belarus', 'BY', 'BLR', 'BYN', '+375', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BE', 'Belgium', 'BE', 'BEL', 'EUR', '+32', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('BZ', 'Belize', 'BZ', 'BLZ', 'BZD', '+501', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BJ', 'Benin', 'BJ', 'BEN', 'XOF', '+229', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BT', 'Bhutan', 'BT', 'BTN', 'BTN', '+975', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BO', 'Bolivia', 'BO', 'BOL', 'BOB', '+591', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BA', 'Bosnia and Herzegovina', 'BA', 'BIH', 'BAM', '+387', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('BW', 'Botswana', 'BW', 'BWA', 'BWP', '+267', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BR', 'Brazil', 'BR', 'BRA', 'BRL', '+55', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city", "state", "postal_code"]}', true),
  ('BN', 'Brunei', 'BN', 'BRN', 'BND', '+673', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('BG', 'Bulgaria', 'BG', 'BGR', 'BGN', '+359', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('BF', 'Burkina Faso', 'BF', 'BFA', 'XOF', '+226', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('BI', 'Burundi', 'BI', 'BDI', 'BIF', '+257', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CV', 'Cabo Verde', 'CV', 'CPV', 'CVE', '+238', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('KH', 'Cambodia', 'KH', 'KHM', 'KHR', '+855', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('CM', 'Cameroon', 'CM', 'CMR', 'XAF', '+237', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CF', 'Central African Republic', 'CF', 'CAF', 'XAF', '+236', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TD', 'Chad', 'TD', 'TCD', 'XAF', '+235', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CL', 'Chile', 'CL', 'CHL', 'CLP', '+56', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('CN', 'China', 'CN', 'CHN', 'CNY', '+86', '{"format": ["postal_code", "state", "city", "street"], "required": ["street", "city", "state", "postal_code"]}', true),
  ('CO', 'Colombia', 'CO', 'COL', 'COP', '+57', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('KM', 'Comoros', 'KM', 'COM', 'KMF', '+269', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CG', 'Congo', 'CG', 'COG', 'XAF', '+242', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CD', 'Congo (DRC)', 'CD', 'COD', 'CDF', '+243', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('CR', 'Costa Rica', 'CR', 'CRI', 'CRC', '+506', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('CI', 'Côte d''Ivoire', 'CI', 'CIV', 'XOF', '+225', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('HR', 'Croatia', 'HR', 'HRV', 'EUR', '+385', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('CU', 'Cuba', 'CU', 'CUB', 'CUP', '+53', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('CY', 'Cyprus', 'CY', 'CYP', 'EUR', '+357', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('CZ', 'Czech Republic', 'CZ', 'CZE', 'CZK', '+420', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('DK', 'Denmark', 'DK', 'DNK', 'DKK', '+45', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('DJ', 'Djibouti', 'DJ', 'DJI', 'DJF', '+253', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('DM', 'Dominica', 'DM', 'DMA', 'XCD', '+1-767', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('DO', 'Dominican Republic', 'DO', 'DOM', 'DOP', '+1-809', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('EC', 'Ecuador', 'EC', 'ECU', 'USD', '+593', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('EG', 'Egypt', 'EG', 'EGY', 'EGP', '+20', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('SV', 'El Salvador', 'SV', 'SLV', 'USD', '+503', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('GQ', 'Equatorial Guinea', 'GQ', 'GNQ', 'XAF', '+240', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('ER', 'Eritrea', 'ER', 'ERI', 'ERN', '+291', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('EE', 'Estonia', 'EE', 'EST', 'EUR', '+372', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('SZ', 'Eswatini', 'SZ', 'SWZ', 'SZL', '+268', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('ET', 'Ethiopia', 'ET', 'ETH', 'ETB', '+251', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('FJ', 'Fiji', 'FJ', 'FJI', 'FJD', '+679', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('FI', 'Finland', 'FI', 'FIN', 'EUR', '+358', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('GA', 'Gabon', 'GA', 'GAB', 'XAF', '+241', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('GM', 'Gambia', 'GM', 'GMB', 'GMD', '+220', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('GE', 'Georgia', 'GE', 'GEO', 'GEL', '+995', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('GH', 'Ghana', 'GH', 'GHA', 'GHS', '+233', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('GR', 'Greece', 'GR', 'GRC', 'EUR', '+30', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('GD', 'Grenada', 'GD', 'GRD', 'XCD', '+1-473', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('GT', 'Guatemala', 'GT', 'GTM', 'GTQ', '+502', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('GN', 'Guinea', 'GN', 'GIN', 'GNF', '+224', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('GW', 'Guinea-Bissau', 'GW', 'GNB', 'XOF', '+245', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('GY', 'Guyana', 'GY', 'GUY', 'GYD', '+592', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('HT', 'Haiti', 'HT', 'HTI', 'HTG', '+509', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('HN', 'Honduras', 'HN', 'HND', 'HNL', '+504', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('HU', 'Hungary', 'HU', 'HUN', 'HUF', '+36', '{"format": ["city", "street", "postal_code"], "required": ["street", "city", "postal_code"]}', true),
  ('IS', 'Iceland', 'IS', 'ISL', 'ISK', '+354', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('IN', 'India', 'IN', 'IND', 'INR', '+91', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city", "state", "postal_code"]}', true),
  ('ID', 'Indonesia', 'ID', 'IDN', 'IDR', '+62', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('IR', 'Iran', 'IR', 'IRN', 'IRR', '+98', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('IQ', 'Iraq', 'IQ', 'IRQ', 'IQD', '+964', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('IE', 'Ireland', 'IE', 'IRL', 'EUR', '+353', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('IL', 'Israel', 'IL', 'ISR', 'ILS', '+972', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('IT', 'Italy', 'IT', 'ITA', 'EUR', '+39', '{"format": ["street", "postal_code", "city", "state"], "required": ["street", "city", "postal_code"]}', true),
  ('JM', 'Jamaica', 'JM', 'JAM', 'JMD', '+1-876', '{"format": ["street", "city", "state"], "required": ["street", "city"]}', true),
  ('JO', 'Jordan', 'JO', 'JOR', 'JOD', '+962', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('KZ', 'Kazakhstan', 'KZ', 'KAZ', 'KZT', '+7', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('KE', 'Kenya', 'KE', 'KEN', 'KES', '+254', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('KI', 'Kiribati', 'KI', 'KIR', 'AUD', '+686', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('KP', 'North Korea', 'KP', 'PRK', 'KPW', '+850', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('KR', 'South Korea', 'KR', 'KOR', 'KRW', '+82', '{"format": ["state", "city", "street", "postal_code"], "required": ["street", "city", "postal_code"]}', true),
  ('KW', 'Kuwait', 'KW', 'KWT', 'KWD', '+965', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('KG', 'Kyrgyzstan', 'KG', 'KGZ', 'KGS', '+996', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LA', 'Laos', 'LA', 'LAO', 'LAK', '+856', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LV', 'Latvia', 'LV', 'LVA', 'EUR', '+371', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LB', 'Lebanon', 'LB', 'LBN', 'LBP', '+961', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LS', 'Lesotho', 'LS', 'LSO', 'LSL', '+266', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LR', 'Liberia', 'LR', 'LBR', 'LRD', '+231', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('LY', 'Libya', 'LY', 'LBY', 'LYD', '+218', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('LI', 'Liechtenstein', 'LI', 'LIE', 'CHF', '+423', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('LT', 'Lithuania', 'LT', 'LTU', 'EUR', '+370', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('LU', 'Luxembourg', 'LU', 'LUX', 'EUR', '+352', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MG', 'Madagascar', 'MG', 'MDG', 'MGA', '+261', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MW', 'Malawi', 'MW', 'MWI', 'MWK', '+265', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('MY', 'Malaysia', 'MY', 'MYS', 'MYR', '+60', '{"format": ["street", "postal_code", "city", "state"], "required": ["street", "city", "postal_code"]}', true),
  ('MV', 'Maldives', 'MV', 'MDV', 'MVR', '+960', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('ML', 'Mali', 'ML', 'MLI', 'XOF', '+223', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('MT', 'Malta', 'MT', 'MLT', 'EUR', '+356', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('MH', 'Marshall Islands', 'MH', 'MHL', 'USD', '+692', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('MR', 'Mauritania', 'MR', 'MRT', 'MRU', '+222', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('MU', 'Mauritius', 'MU', 'MUS', 'MUR', '+230', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('FM', 'Micronesia', 'FM', 'FSM', 'USD', '+691', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('MD', 'Moldova', 'MD', 'MDA', 'MDL', '+373', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MC', 'Monaco', 'MC', 'MCO', 'EUR', '+377', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MN', 'Mongolia', 'MN', 'MNG', 'MNT', '+976', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('ME', 'Montenegro', 'ME', 'MNE', 'EUR', '+382', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MA', 'Morocco', 'MA', 'MAR', 'MAD', '+212', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('MZ', 'Mozambique', 'MZ', 'MOZ', 'MZN', '+258', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('MM', 'Myanmar', 'MM', 'MMR', 'MMK', '+95', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NA', 'Namibia', 'NA', 'NAM', 'NAD', '+264', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NR', 'Nauru', 'NR', 'NRU', 'AUD', '+674', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('NP', 'Nepal', 'NP', 'NPL', 'NPR', '+977', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NL', 'Netherlands', 'NL', 'NLD', 'EUR', '+31', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('NZ', 'New Zealand', 'NZ', 'NZL', 'NZD', '+64', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NI', 'Nicaragua', 'NI', 'NIC', 'NIO', '+505', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NE', 'Niger', 'NE', 'NER', 'XOF', '+227', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('NG', 'Nigeria', 'NG', 'NGA', 'NGN', '+234', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('MK', 'North Macedonia', 'MK', 'MKD', 'MKD', '+389', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('NO', 'Norway', 'NO', 'NOR', 'NOK', '+47', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('OM', 'Oman', 'OM', 'OMN', 'OMR', '+968', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PK', 'Pakistan', 'PK', 'PAK', 'PKR', '+92', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PW', 'Palau', 'PW', 'PLW', 'USD', '+680', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PS', 'Palestine', 'PS', 'PSE', 'ILS', '+970', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PA', 'Panama', 'PA', 'PAN', 'PAB', '+507', '{"format": ["street", "city", "state"], "required": ["street", "city"]}', true),
  ('PG', 'Papua New Guinea', 'PG', 'PNG', 'PGK', '+675', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PY', 'Paraguay', 'PY', 'PRY', 'PYG', '+595', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('PE', 'Peru', 'PE', 'PER', 'PEN', '+51', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('PH', 'Philippines', 'PH', 'PHL', 'PHP', '+63', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('PL', 'Poland', 'PL', 'POL', 'PLN', '+48', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('PT', 'Portugal', 'PT', 'PRT', 'EUR', '+351', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('QA', 'Qatar', 'QA', 'QAT', 'QAR', '+974', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('RO', 'Romania', 'RO', 'ROU', 'RON', '+40', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('RU', 'Russia', 'RU', 'RUS', 'RUB', '+7', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city", "postal_code"]}', true),
  ('RW', 'Rwanda', 'RW', 'RWA', 'RWF', '+250', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('KN', 'Saint Kitts and Nevis', 'KN', 'KNA', 'XCD', '+1-869', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('LC', 'Saint Lucia', 'LC', 'LCA', 'XCD', '+1-758', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('VC', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'XCD', '+1-784', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('WS', 'Samoa', 'WS', 'WSM', 'WST', '+685', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SM', 'San Marino', 'SM', 'SMR', 'EUR', '+378', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('ST', 'São Tomé and Príncipe', 'ST', 'STP', 'STN', '+239', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SA', 'Saudi Arabia', 'SA', 'SAU', 'SAR', '+966', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('SN', 'Senegal', 'SN', 'SEN', 'XOF', '+221', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('RS', 'Serbia', 'RS', 'SRB', 'RSD', '+381', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('SC', 'Seychelles', 'SC', 'SYC', 'SCR', '+248', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SL', 'Sierra Leone', 'SL', 'SLE', 'SLE', '+232', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SG', 'Singapore', 'SG', 'SGP', 'SGD', '+65', '{"format": ["street", "postal_code"], "required": ["street", "postal_code"]}', true),
  ('SK', 'Slovakia', 'SK', 'SVK', 'EUR', '+421', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('SI', 'Slovenia', 'SI', 'SVN', 'EUR', '+386', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('SB', 'Solomon Islands', 'SB', 'SLB', 'SBD', '+677', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SO', 'Somalia', 'SO', 'SOM', 'SOS', '+252', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('ZA', 'South Africa', 'ZA', 'ZAF', 'ZAR', '+27', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('SS', 'South Sudan', 'SS', 'SSD', 'SSP', '+211', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('ES', 'Spain', 'ES', 'ESP', 'EUR', '+34', '{"format": ["street", "postal_code", "city", "state"], "required": ["street", "city", "postal_code"]}', true),
  ('LK', 'Sri Lanka', 'LK', 'LKA', 'LKR', '+94', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('SD', 'Sudan', 'SD', 'SDN', 'SDG', '+249', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('SR', 'Suriname', 'SR', 'SUR', 'SRD', '+597', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('SE', 'Sweden', 'SE', 'SWE', 'SEK', '+46', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('CH', 'Switzerland', 'CH', 'CHE', 'CHF', '+41', '{"format": ["street", "postal_code", "city"], "required": ["street", "city", "postal_code"]}', true),
  ('SY', 'Syria', 'SY', 'SYR', 'SYP', '+963', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TW', 'Taiwan', 'TW', 'TWN', 'TWD', '+886', '{"format": ["postal_code", "city", "street"], "required": ["street", "city", "postal_code"]}', true),
  ('TJ', 'Tajikistan', 'TJ', 'TJK', 'TJS', '+992', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('TZ', 'Tanzania', 'TZ', 'TZA', 'TZS', '+255', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('TH', 'Thailand', 'TH', 'THA', 'THB', '+66', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('TL', 'Timor-Leste', 'TL', 'TLS', 'USD', '+670', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TG', 'Togo', 'TG', 'TGO', 'XOF', '+228', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TO', 'Tonga', 'TO', 'TON', 'TOP', '+676', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TT', 'Trinidad and Tobago', 'TT', 'TTO', 'TTD', '+1-868', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('TN', 'Tunisia', 'TN', 'TUN', 'TND', '+216', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('TR', 'Turkey', 'TR', 'TUR', 'TRY', '+90', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('TM', 'Turkmenistan', 'TM', 'TKM', 'TMT', '+993', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('TV', 'Tuvalu', 'TV', 'TUV', 'AUD', '+688', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('UG', 'Uganda', 'UG', 'UGA', 'UGX', '+256', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('UA', 'Ukraine', 'UA', 'UKR', 'UAH', '+380', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('AE', 'United Arab Emirates', 'AE', 'ARE', 'AED', '+971', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('UY', 'Uruguay', 'UY', 'URY', 'UYU', '+598', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('UZ', 'Uzbekistan', 'UZ', 'UZB', 'UZS', '+998', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('VU', 'Vanuatu', 'VU', 'VUT', 'VUV', '+678', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('VA', 'Vatican City', 'VA', 'VAT', 'EUR', '+39', '{"format": ["street", "postal_code", "city"], "required": ["street", "city"]}', true),
  ('VE', 'Venezuela', 'VE', 'VEN', 'VES', '+58', '{"format": ["street", "city", "state", "postal_code"], "required": ["street", "city"]}', true),
  ('VN', 'Vietnam', 'VN', 'VNM', 'VND', '+84', '{"format": ["street", "city", "state"], "required": ["street", "city"]}', true),
  ('YE', 'Yemen', 'YE', 'YEM', 'YER', '+967', '{"format": ["street", "city"], "required": ["street", "city"]}', true),
  ('ZM', 'Zambia', 'ZM', 'ZMB', 'ZMW', '+260', '{"format": ["street", "city", "postal_code"], "required": ["street", "city"]}', true),
  ('ZW', 'Zimbabwe', 'ZW', 'ZWE', 'ZWL', '+263', '{"format": ["street", "city"], "required": ["street", "city"]}', true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  iso_code_2 = EXCLUDED.iso_code_2,
  iso_code_3 = EXCLUDED.iso_code_3,
  currency_code = EXCLUDED.currency_code,
  phone_prefix = EXCLUDED.phone_prefix,
  address_format = EXCLUDED.address_format,
  is_active = EXCLUDED.is_active,
  updated_at = now();