// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kixsdhnfzjnxikmnbipi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeHNkaG5mempueGlrbW5iaXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQ2NDgsImV4cCI6MjA2NjYxMDY0OH0.bFcMmpvwle1l3JgDfwS71x_-LoYM_Ze-GteNMBd7JQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  },
  global: {
    fetch: (url, options: RequestInit = {}) => {
      // Longer timeout for auth requests (login can be slow on mobile) and edge functions (translations)
      const isAuthRequest = typeof url === 'string' && url.includes('/auth/');
      const isEdgeFunction = typeof url === 'string' && url.includes('/functions/');
      const isStorageUpload = typeof url === 'string' && url.includes('/storage/');
      const timeout = isAuthRequest ? 60000 : isEdgeFunction ? 300000 : isStorageUpload ? 120000 : 30000;
      
      const controller = new AbortController();
      const timeoutId = setTimeout(() => {
        controller.abort(new Error('Request timeout'));
      }, timeout);
      
      // Combine caller's signal with our timeout signal (don't overwrite)
      const existingSignal = options.signal;
      if (existingSignal) {
        existingSignal.addEventListener('abort', () => {
          controller.abort(existingSignal.reason);
          clearTimeout(timeoutId);
        });
      }
      
      return fetch(url, {
        ...options,
        signal: controller.signal,
      }).finally(() => clearTimeout(timeoutId));
    },
  },
});